name: install_ubuntu_deps
runs:
  using: composite
  steps:
  - name: install cmake
    # OpenEXR requires CMake 3.12.
    run: |
      echo $(date +%F) > ./date
      echo $(git ls-remote https://github.com/facebookresearch/partnr-planner.git HEAD | awk '{ print $1}') > ./partnr_sha
      cat ./partnr_sha
      wget https://cmake.org/files/v3.12/cmake-3.12.4-Linux-x86_64.sh
      sudo mkdir /opt/cmake312
      sudo sh ./cmake-3.12.4-Linux-x86_64.sh --prefix=/opt/cmake312 --skip-license
      sudo ln -s /opt/cmake312/bin/cmake /usr/local/bin/cmake
      sudo ln -s /opt/cmake312/bin/ctest /usr/local/bin/ctest
    shell: bash
  - name: Install dependencies
    run: |-
      echo "Install dependencies"
      sudo apt-get update || true
      sudo apt-get install -y --no-install-recommends \
        build-essential \
        git \
        git-lfs \
        curl \
        vim \
        ca-certificates \
        libjpeg-dev \
        libglm-dev \
        libegl1-mesa-dev \
        ninja-build \
        xorg-dev \
        freeglut3-dev \
        pkg-config \
        wget \
        zip \
        lcov\
        libhdf5-dev \
        libomp-dev \
        unzip || true
      #install doc build deps
      sudo apt install --yes --allow-change-held-packages \
        texlive-base \
        texlive-latex-extra \
        texlive-fonts-extra \
        texlive-fonts-recommended
    shell: bash
  - name: Setup miniconda
    uses: conda-incubator/setup-miniconda@v3.0.1
    with:
      miniconda-version: "latest"
      python-version: "3.9"
      activate-environment: "partnr"
  - name: Install conda dependencies
    run: |-
      echo "Install conda and dependencies"
      conda install -q -y mkl==2021.4.0
      conda install -q -y -c conda-forge ninja ccache
      conda install -q -y -c conda-forge libglib=2.76.1 glib=2.76.1 glib-tools=2.76.1
      conda install -y -c conda-forge numpy==1.26.4 pytest pytest-cov hypothesis pytest-mock
      pip install pytest-sugar pytest-xdist pytest-benchmark opencv-python cython mock
    shell: bash -el {0}
